image: maven:3.8.5-eclipse-temurin-17-alpine

variables:
  DOCKER_IMAGE: 211125330771.dkr.ecr.eu-central-1.amazonaws.com/lottery
  EC2_HOST: ec2-user@3.64.125.147

stages:
  - build
  - package
  - deploy

maven-build:
  stage: build
  only:
    - master
  script:
    - ./mvnw clean package -DskipTests  # Skip tests for faster build, remove -DskipTests if you want to run tests
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 hour

docker-build:
  stage: package
  only:
    - master
  before_script:
    - apk add --no-cache docker aws-cli
    - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin $DOCKER_IMAGE
  script:
    - docker build -t $DOCKER_IMAGE:latest .
    - docker push $DOCKER_IMAGE:latest

deploy:
  stage: deploy
  only:
    - master
  before_script:
    - apk add --no-cache openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - scp docker-compose.yml $EC2_HOST:~/
    - |
      ssh $EC2_HOST '
        aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin $DOCKER_IMAGE
        docker-compose down
        docker-compose pull lottery
        docker-compose up -d
      '