spring:
  cache:
    type: redis
    redis:
      time-to-live: PT30M
  data:
    mongodb:
      uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB_NAME}?authSource=${MONGO_AUTH_SOURCE}
    redis:
      port: ${REDIS_PORT:63792}
      host: ${REDIS_HOST:localhost}
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
lotto:
  result-checker:
    frequency: "0 0 12 * * 6"
  number-generator:
    frequency: "0 55 11 * * 6"
    facade:
      minBound: 1
      maxBound: 99
      count: 25
    http:
      client:
        config:
          uri: http://ec2-3-120-147-150.eu-central-1.compute.amazonaws.com
          port: 9090
          connectionTimeout: 5000
          readTimeout: 5000

jwt:
  authentication:
    secretKey: ${SECRET_KEY}
    expirationDays: 30
    issuer: lotto-backend-service

server:
  port: 8000