spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/lotto-web
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
lotto:
  result-checker:
    frequency: "0 55 11 * * 6"
  number-generator:
    frequency: "0 0 12 * * 6"
    facade:
      minBound: 1
      maxBound: 99
      count: 25
    http:
      client:
        config:
          uri: http://ec2-3-120-147-150.eu-central-1.compute.amazonaws.com
          port: 9090
          connectionTimeout: 5000
          readTimeout: 5000

jwt:
  authentication:
    secret-key: ${SECRET_KEY}
    expires-at: 30
    issuer: lotto-backend-service