lotto:
  number-generator:
    frequency: "*/12 * * * * *"
  result-checker:
    frequency: "*/15 * * * * *"

jwt:
  authentication:
    expirationDays: 10000

spring:
  cache:
    type: none
    redis:
      time-to-live: PT10S